events {}

http {
    include /etc/nginx/mime.types;

    log_format main '$remote_addr - [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent" '
                    'upstream=$upstream_addr';

    access_log /var/log/nginx/access.log main;
    error_log  /var/log/nginx/error.log;

    include /etc/nginx/conf.d/*.conf;
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;
}