events {}

http {
    include /etc/nginx/mime.types;

    log_format main '$remote_addr - $request '
                    'status=$status upstream=$upstream_addr';

    access_log /var/log/nginx/access.log main;

    include /etc/nginx/conf.d/*.conf;
}